### ISSUE TITLE
[ENHANCEMENT] Appwrite에 대해

### ISSUE THREAD

**Issue by hookSSi** [hookSSi/RobotChef#1]
**개선 필요한 기능**
현재 Appwrite는 회원관리 즉 회원가입, 로그인, 즐겨찾기 용도로만 사용하고 있다.

하지만 쓸데없이 크고 opensource라서 뭐가 문제인지 파악하기도 힘들다. (현재 한번씩 통신이 안되는 문제가 생김 https 관련 문제인것 같기도...)

이것을 대체할 수 있지 않을까?

**내가 생각한 해결법**
Flask에 간단하게 DB를 만들어서 연동시킨다.

아주 간단한 DB를 사용해서 ex) sqlite 

flask의 sqlalchemy를 사용해서 간단하게 회원가입, 로그인, 즐겨찾기를 구현해보는 건 어떨까?

**Comment by Syne-ss** [comment]
AppWrite를 제거했으니 Close해도 될 듯 합니다
