### ISSUE TITLE
[QUESTION] 질문 몇 가지 작성합니다.

### ISSUE THREAD

**Issue by Syne-ss** [hookSSi/RobotChef#13]
**질문거리**
1. 기기 호환 문제
최소 SDK 버전을 낮춰
이전처럼 애플리케이션 설치 중 파싱 문제가 발생하지는 않으나
기기와 호환되지 않아 설치되지 않는 문제 문제 발생

호환되지 않는 기기 : 삼성 갤럭시 노트 5, 롤리팝 7.0

2. 검색 및 즐겨찾기 기능에서 네트워크 대기 시 보이는
하늘색 로딩 애니메이션을 gif 파일로 대체할 수 있는지?

3. 검색 및 즐겨찾기 화면에서 네트워크 연결 여부에 따라 경고 메시지를
출력시킬 수 있는지?

**Comment by hookSSi** [comment]
1, 2 수정 완료 했고
3은 경고 메시지를 출력할 예정입니다.
