### ISSUE TITLE
[ENHANCEMENT] UI 개선

### ISSUE THREAD

**Issue by Syne-ss** [hookSSi/RobotChef#3]
**개선 필요한 기능**
UI 개선이 필요하다고 생각.
요리 레시피와 관련된 애플리케이션인 만큼 배색이 산뜻할 필요가 있을 것임.

**내가 생각한 해결법**
전체적인 색감을 변경
-> 현재 검정색, 회색 등의 무채색 계열로 이루어져 있는데 이를 흰색을 베이스로 하여 연두색, 주황색 등 난색 계열로
구성하면 완성도나 유저 친화적인 측면에서 도움이 될 것이라고 생각함.

**Comment by hookSSi** [comment]
![image](https://user-images.githubusercontent.com/12372136/111730442-c70de700-88b4-11eb-985d-15d2aeb940c4.png)

난색은 이런거!

**Comment by hookSSi** [comment]
![image](https://user-images.githubusercontent.com/12372136/111897386-05490900-8a63-11eb-8577-550f3c2898e7.png)
![image](https://user-images.githubusercontent.com/12372136/111897391-0b3eea00-8a63-11eb-9974-52c6236d941f.png)
![image](https://user-images.githubusercontent.com/12372136/111897396-13972500-8a63-11eb-8987-fd33919c15a7.png)
![image](https://user-images.githubusercontent.com/12372136/111897408-29a4e580-8a63-11eb-8aa9-d183601affa8.png)

다음처럼 UI 색스타일을 변경함
